logging:
  level:
    root: INFO

spring:
  application:
    name: app-peoplety-gateway
  main:
    web-application-type: reactive
  cloud:
    # 配置 路由网关
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes:
        #=============================================================用户微服务
        - id: user-route
          #  要使用注册中心的服务：lb://{注册的服务名}
          uri: lb://app-peoplety-user
          # 路由断言Factories
          predicates:
            - Path=/user/**
          filters:
            # 转发请求时去掉1级前缀
            - StripPrefix=1
            #请求数限流
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@ipKeyResolver}'
                #令牌桶每秒填充平均速率
                redis-rate-limiter.replenishRate: 30
                #令牌桶总容量
                redis-rate-limiter.burstCapacity: 100
        #=============================================================社区微服务
        - id: record-route
          uri: lb://app-peoplety-record
          predicates:
            - Path=/record/**
          filters:
            # 转发请求时去掉1级前缀
            - StripPrefix=1
        #=============================================================系统日志微服务
        - id: log-route
          uri: lb://app-peoplety-log
          predicates:
            - Path=/syslog/**
          filters:
            # 转发请求时去掉1级前缀
            - StripPrefix=1
        #=============================================================分布式ID微服务
        - id: leaf-route
          uri: lb://app-peoplety-leaf
          predicates:
            - Path=/leaf/**
          filters:
            # 转发请求时去掉1级前缀
            - StripPrefix=1
              #请求数限流
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@ipKeyResolver}'
                #令牌桶每秒填充平均速率
                redis-rate-limiter.replenishRate: 30
                #令牌桶总容量
                redis-rate-limiter.burstCapacity: 100
        #==========================================================即时通信微服务 - deprecated
        - id: msg-route
          uri: lb://app-peoplety-im
          predicates:
            - Path=/im/**
          filters:
            # 转发请求时去掉1级前缀
            - StripPrefix=1
# 配置Redis，限流 127.0.0.1可以省略配置
redis:
  host: 127.0.0.1
  port: 6379
server:
  port: 8100
  servlet:
    context-path: "/"
  tomcat:
    # (),/:;<=>?@[\]{}  转发过程中出现的特殊字符
    relaxed-query-chars: [ '[',']','{','}' ]
eureka:
  client:
    serviceUrl:
      defaultZone: http://gaozhi.online:8080/eureka/
  instance:
    instance-id: peoplety-gateway
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true